cancle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,9 +25,16 @@ jobs:
             [ -z "$LAST_LOG" ] && RUN_PIPELINES=0
             
             echo "should run? $RUN_PIPELINES"
-            if [[ $RUN_PIPELINES -eq 0 ]]; then
-              echo "Cancelling pipeline"
+            if [ "$RUN_PIPELINES" -eq "0" ]; then
+              echo "Don't run CI workflows"
               curl --request POST \
+                --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
+                --header "Circle-Token: ${CIRCLE_TOKEN}"
+              sleep 30  # Give cancellation a chance to run. This script then won't continue running.
+              exit 1  # If cancellation didn't run for some reason, fail the build.
+            else 
+              echo 'Run CI workflow'
+                curl --request POST \
                 --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
                 --header "Circle-Token: ${CIRCLE_TOKEN}"
               sleep 30  # Give cancellation a chance to run. This script then won't continue running.
