cancle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,9 +26,12 @@ jobs:
             
             echo "should run? $RUN_PIPELINES"
             if [[ $RUN_PIPELINES -eq 0 ]]; then
+              echo "Cancelling pipeline"
               curl --request POST \
                 --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
                 --header "Circle-Token: ${CIRCLE_TOKEN}"
+              sleep 30  # Give cancellation a chance to run. This script then won't continue running.
+              exit 1  # If cancellation didn't run for some reason, fail the build.
             fi
   fluff:
     docker:
