run the server integration tests, cleanup package scripts, echo helpful errors

diff --git a/packages/server/test/support/helpers/run b/packages/server/test/support/helpers/run
--- a/packages/server/test/support/helpers/run
+++ b/packages/server/test/support/helpers/run
@@ -1,6 +1,21 @@
 SPEC="$1"
 BROWSER="$2"
 
+if [ "$SPEC" == '' ]; then
+  echo 'Error: A path to a spec file must be specified!'
+  echo ''
+  echo 'It should look something like this:'
+  echo ''
+  echo '  $ npm test ./test/unit/api_spec.coffee'
+  echo ''
+  echo 'If you want to run all a specific group of tests:'
+  echo ''
+  echo '  $ npm run test-unit'
+  echo '  $ npm run test-integration'
+  echo ''
+  exit 1
+fi
+
 CYPRESS_DEBUG=true \
 NODE_ENV=test \
 NODE_DEBUG=request \
