.

diff --git a/.github/workflows/trigger-circleci.yml b/.github/workflows/trigger-circleci.yml
--- a/.github/workflows/trigger-circleci.yml
+++ b/.github/workflows/trigger-circleci.yml
@@ -22,9 +22,14 @@ jobs:
         run: |
           echo "Triggering CircleCI pipeline for $GITHUB_HEAD_REF."
 
-          curl -X POST https://circleci.com/api/v2/project/github/cypress-io/cypress/pipeline \
-          --header "Circle-Token:$CIRCLE_TOKEN" \
-          --header "content-type:application/json" \
-          --data "{\"branch\":\"$GITHUB_HEAD_REF\"}" \
-          --write-out "%{http_code}" \
-          --silent
+          response=$(curl -X POST https://circleci.com/api/v2/project/github/cypress-io/cypress/pipeline \
+            --header "Circle-Token:$CIRCLE_TOKEN" \
+            --header "content-type:application/json" \
+            --data "{\"branch\":\"$GITHUB_HEAD_REF\"}" \
+            --silent
+          )
+
+          if [ "$( jq 'has("message")' <<< $response )" == "true" ]; then
+            Echo "Error triggering pipeline."
+            exit 1;
+          fi
