.

diff --git a/.github/workflows/trigger-circleci.yml b/.github/workflows/trigger-circleci.yml
--- a/.github/workflows/trigger-circleci.yml
+++ b/.github/workflows/trigger-circleci.yml
@@ -21,6 +21,11 @@ jobs:
           BASE_ORG_AND_REPO: ${{ github.event.pull_request.head.full_name }}
           PULL_ID: ${{ github.event.pull_request.number }}
         run: |
+          if [[ -z ${CIRCLE_TOKEN+x} ]]; then
+            echo "The CIRCLE_TOKEN is unset. Cannot trigger pipeline..."
+            exit 1;
+          fi
+
           BRANCH="$GITHUB_HEAD_REF"
 
           if [[ "$BASE_ORG_AND_REPO" != "cypress-io/cypress" ]]; then
