.

diff --git a/.github/workflows/trigger-circleci.yml b/.github/workflows/trigger-circleci.yml
--- a/.github/workflows/trigger-circleci.yml
+++ b/.github/workflows/trigger-circleci.yml
@@ -1,7 +1,7 @@
 name: "Trigger CircleCi Pipeline"
 
 on:
-  pull_request:
+  pull_request_target:
     types:
       - opened
       - ready_for_review
@@ -15,21 +15,36 @@ jobs:
       - if: ${{ github.event.pull_request.draft == true }} 
         run: echo "This PR is still in draft. Not triggering the CircleCi Pipeline"
       - if: ${{ github.event.pull_request.draft == false }}
-        # uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
         shell: bash
         env:
           CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
+          BASE_ORG_AND_REPO: ${{ github.event.pull_request.head.full_name }}
+          PULL_ID: ${{ github.event.pull_request.number }}
         run: |
-          echo "Triggering CircleCI pipeline for $GITHUB_HEAD_REF. $GITHUB_REF_NAME & $GITHUB_REPOSITORY_OWNER"
+          if [[ "${CIRCLE_TOKEN}" == "" ]]; then
+            echo "The CIRCLE_TOKEN is unset. Cannot trigger pipeline..."
+            exit 1;
+          fi
+
+          BRANCH="$GITHUB_HEAD_REF"
+
+          if [[ "$BASE_ORG_AND_REPO" != "cypress-io/cypress" ]]; then
+            echo "Triggering CircleCi pipeline for outside contributor."
+            BRANCH="pull/$PULL_ID/head"
+          fi
+
+          echo "Triggering CircleCi pipeline for $BRANCH"
 
           response=$(curl -X POST https://circleci.com/api/v2/project/github/cypress-io/cypress/pipeline \
             --header "Circle-Token:$CIRCLE_TOKEN" \
             --header "content-type:application/json" \
-            --data "{\"branch\":\"$GITHUB_HEAD_REF\"}" \
+            --data "{\"branch\":\"$BRANCH\"}" \
             --silent
           )
 
+          echo "$response"
+
           if [ "$(jq 'has("message")' <<< $response )" == "true" ]; then
-            echo "error triggering"
+            echo "Error triggering pipeline..."
             exit 1;
           fi
